name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Appium Maven Demos
      run: mvn clean test -Dtest="helloworld.*Tests"
      working-directory: appium/appium-maven-demos
    - name: Appium Gradle Demos
      run: ./gradlew clean test --tests "helloworld.*"
      working-directory: appium/appium-gradle-demos
